project:
  type: website
  preview:
    port: 4611
  render:
  - '*.qmd'
  - '!misc/'
  resources:
  - slides_1_linear_regression.html
  - slides_2_properties.html
  - slides_3_specification.html
  - slides_4_model_selection.html
  - sim_results.RDS
  output-dir: docs
execute:
  freeze: auto
website:
  title: Econometrics M1
  favicon: images/favicon.ico
  site-url: https://vincentbagilet.github.io/metrics_m1_2024/
  repo-url: https://github.com/vincentbagilet/metrics_m1_2024
  navbar:
    left:
    - text: Lectures
      menu:
      - text: 1 - Linear Regression
        href: content/1_linear_regression.qmd
      - text: 2 - OLS Properties
        href: content/2_properties.qmd
      - text: 3 - Model Specification
        href: content/3_specification.qmd
      - text: 4 - Model Selection
        href: content/4_model_selection.qmd
    - text: Exercises
      menu:
      - text: 1 - Hands-on Linear Regression
        href: content/exercises/ex_01_linear_regression.qmd
      - text: 2 - Specification
        href: content/exercises/ex_02_specification.qmd
    - href: content/syllabus.qmd
      text: Syllabus
    - href: content/definitions.qmd
      text: Definitions
    - href: content/resources.qmd
      text: Resources
  page-footer:
    right: |
      Made with R and [Quarto](https://quarto.org/)<br>
      [Source code on GitHub](https://github.com/vincentbagilet/metrics_m1_2024)
format:
  html:
    toc: true
    theme: vb.scss
    css: include/webex.css
    include-after-body: include/webex.js
editor: visual
