project:
  type: website
  preview:
    port: 4611
  render: 
    - "*.qmd"
    - "!slides/"
    - "!misc/"
  output-dir: _site
    
execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Econometrics M1"
  favicon: images/favicon.ico
  navbar:
    left:
      - text: "Lectures"
        menu:
          - text: "1 - Linear Regression"
            href: content/1_linear_regression.qmd
          - text: "2 - OLS Properties"
            href: content/2_ols_properties.qmd
          - text: "3 - Model Specification"
            href: content/3_model_specification.qmd
          - text: "4 - Covariates Selection"
            href: content/4_covariates_selection.qmd
      - href: content/syllabus.qmd
        text: "Syllabus"
      - href: content/definitions.qmd
        text: "Definitions"
      - href: content/resources.qmd
        text: "Resources"
  page-footer:
    right: |
      Made with R and [Quarto](https://quarto.org/)<br>
      [Source code on GitHub]()


format:
  html:
    toc: true
    theme:
      - vb.scss

editor: visual


