---
title: "Lecture 1 - Linear Regression"
subtitle: "<br> MSc Advanced Economics"
author: "Vincent Bagilet"
date: "2024-09-17"
output:
  xaringan::moon_reader:
    self_contained: true
    lib_dir: libs
    css: mediocre-themer.css
    nature:
      countIncrementalSlides: no
      highlightLines: yes
      highlightStyle: github
      ratio: '16:9'
      titleSlideClass: [right, middle, inverse]
---

```{r themer, include=FALSE}
library(mediocrethemes)
library(here)

# set knit directory to "Document directory"

xaringan_mediocre(pal = "portal")
```

class: titled, middle

# Objectives

- Equip you with tools to quantitatively explore relevant social science questions

- Focus on intuitions

- Actual data sets and simulated data

???

- Simulated data enable to know how the data is generated and therefore to study the influence of various factors and assumptions on the outcome of our analysis
- Provide you with tools to check hypotheses yourself

---
class: right, middle, inverse

# Logistics

---
class: titled, middle

# Structure

- I will teach the 4 first lectures (`r fontawesome::fa("envelope")`  [vincent.bagilet@gmail.com](vincent.bagilet@gmail.com))

- Gaetan Bakalli will teach the 4 last ones (`r fontawesome::fa("envelope")`  [bakalli@em-lyon.com](bakalli@em-lyon.com))

- Lucile Laugrette will teach a R TD (`r fontawesome::fa("envelope")`  [lucile.laugerette@gmail.com ](lucile.laugerette@gmail.com ))

- 

---
class: titled, middle

# Website

- All the materials and information can be found on the class' website

- Lectures 

- Definitions

- Additional Resources






