---
title: "Linear Regression"
subtitle: "Introduction and refresher to linear regression"
published-title: "Date"
date: "2024-09-17"
self-contained: true
engine: knitr
---

::: callout-tip
## Objective

In this session, we will review the basics of linear regression.
:::

## Materials

`r fontawesome::fa("file-powerpoint")` [Open slides](../slides/lecture_1/slides_1_linear_regression.html)

```{r out.width='100%'}
#| echo: false

knitr::include_url("https://vincentbagilet.github.io/metrics_m2_2024/slides/lecture_1/slides_1_linear_regression.html")
```


## Session Outline

1.  Introduction: estimating a production function
1.  Course logistics
1.  Example: the link between the level of education and earnings
1.  Exercise (optional)
1.  Mathematical derivation of the OLS estimator

<!-- ## Exercise -->

<!-- *This section will describe the exercise that we will do in class and provide links to the data sets and tools used.* -->

<!-- Since the TDs have not yet started, we will use Google Collabs to run today's code online. In the future, you will use R Studio. -->

## Additional Resources

-   [Seeing Theory](https://seeing-theory.brown.edu/) provides a nice introduction to probability and statistics based on interactive web applications
-   The material from your L3 econometrics class
-   [Chapter 2 of *The Effect*](https://theeffectbook.net/ch-ResearchQuestions.html) on good research questions
-   [Chapter 4 of *The Effect*](https://theeffectbook.net/ch-DescribingRelationships.html) for a review of linear regression
-   [Chapter 3 of Sciences Po's *Introduction to Econometrics with R*](https://scpoecon.github.io/ScPoEconometrics/linreg.html): same
-   [MLU-explain on linear regression](https://mlu-explain.github.io/linear-regression/): same but from a machine learning perspective
