---
title: "Definitions, Terminology and Notations"
subtitle: "A repository of potentially useful definitions, terminology and notations"
engine: knitr
format: 
  html:
    page-layout: full
html-math-method: mathml
---

## Terminology and notation

For $n$ *individuals* indexed by $i$ ($i = 1,\dots,n$), in the linear regression model $y_i = \beta_0 + \beta_1 x_{1i} + ... + \beta_k x_{ki} + e_i$,

-   $y$ is called the *dependent variable*, the *regressand*, the *explained variable*, or the *left-hand side variable*,
-   $x_{1}, ..., x_{k}$ are the $k$ *independent variables*, the *regressors*, the *explanatory variables*, or the *right-hand side variables*,
-   $x \mapsto \beta_0 + \beta_1 x$ is the *population regression function*,
-   $\beta_0$ is the *intercept*,
-   $\beta_1$ is the *slope* parameter associated with $x_1$,
-   Together $\beta_0$ and $\beta_1$ are the *coefficients* or *parameters* of the regression model,
-   $e_i$ is the *error* or *disturbance* term.

In vector form, this is equivalent to $y = \beta_0 + \beta_1 x_1 + ... + \beta_k x_{k} + e$ where:

$$y = \begin{bmatrix}
                    y_1\\ 
                    \vdots\\
                    y_n
                \end{bmatrix}_{n\times 1},
    \quad       \forall j \in \{1, .., k\} \quad
     x_j = \begin{bmatrix}
                    x_{j,1}\\ 
                    \vdots\\
                    x_{j,n}
                \end{bmatrix}_{n\times 1}
     \quad and \quad        
     e = \begin{bmatrix}
                    e_1\\ 
                    \vdots\\
                    e_n
                \end{bmatrix}_{n\times 1}$$

In matrix form, this equivalent to $y = X\beta + e$ where:

$$X = \begin{bmatrix}
            1 & x_{1,1} & ... & x_{k,1}\\ 
            1 & x_{1,2} & ... & x_{k,2}\\ 
            \vdots & \vdots & & \vdots\\
            1 & x_{1,n} & ... & x_{k,n}\\ 
        \end{bmatrix}_{n\times (k + 1)}
      \quad and \quad   
      \beta = \begin{bmatrix}
                    \beta_{0}\\ 
                    \vdots\\
                    \beta_{k}
                \end{bmatrix}_{(k+1)\times 1}
                $$

::: callout-note
In this class, vectors are in lower case (*eg* $y$) and matrices in caps (*eg* $X$). Most of the time, individual observations will be indexed by $i$ (*eg* $y_i$); these are scalars.
:::

## Definitions

```{r}
#| label: definition_table
#| echo: false
#| message: false

library(tidyverse)
library(readxl)
library(DT)

definitions <- read_excel("definitions.xlsx")

definitions |> 
  dplyr::arrange(Word) |> 
  DT::datatable(
    filter = 'top', 
    escape = FALSE,
    options = list(
      pageLength = 10,
      scrollY = TRUE,
      scrollX = TRUE,
      autoWidth = TRUE
    )
  )
```
